### PR TITLE
Add metadata to Logstash events

### PR DESCRIPTION
**Pull request by joshuaspence**
We have two separate S3 buckets which are setup to notify an SQS queue on object creation. One of these queues is used for ELB access logs and the other is used for S3 access logs. I want to send these logs to the same SQS queue, but doing so would make it impossible to differentiate the different types of logs. To fix this, I have added `[@metadata][s3_bucket_name]` and `[@metadata][s3_object_key]` fields to events that are emitted from the `s3sqs` input plugin. This then allows me to set the type using a filter:

```
filter {
  if [@metadata][s3_bucket_name] == "my-elb-logs-bucket" {
    mutate {
      add_field => {
        "type" => "elb"
      }
    }
  } else if [@metadata][s3_bucket_name] == "my-s3-logs-bucket" {
    mutate {
      add_field => {
        "type" => "s3"
      }
    }
  }
}
```

### CODE REVIEW

**Comment by Heiko-san** [comment]
Hi, 

this looks like a good idea and should not break any setup, I think.
So I tend to merge this.
Although I'm not sure if the object key really is necessary/reasonable information since the s3 file is only meant as a temporary storage.
You don't seam to use this information after all (?)
I think this will be useless information which will bump up elasticsearch index for no reason if you have setups with about 50 to 100 ELBs.

Do you have a use case where this information would be useful ?

**Comment by joshuaspence** [comment]
I don't have an immediate use case for the object key, I only added it for completeness. I suppose that it could be useful though, if you have multiple ELBs writing access logs to the same bucket but each using a different prefix.

In any case, this shouldn't impact on any storage requirements because data contained in the `@metadata` field is not sent to the output.

**Comment by Heiko-san** [comment]
Ah ok , didn't know that, actually although I wrote this plugin I'm not very experienced with logstash.

**Comment by joshuaspence** [comment]
Thanks for merging. Any chance of publishing a new release?

**Pull request merged**
